### ISSUE TITLE
Erklärung zu Schritt 2 (readme)

### ISSUE THREAD

**Issue by mansle** [derzoelli/Binnen-I-be-gone-for-MacOS#1]
Vielen Dank für deine Arbeit. Ich würde die Erweiterung gern nutzen, kenne mich aber mit Github nicht aus. Könntest du Schritt 2 in der Readme für unerfahrene GitHub Nutzer noch näher ausführen?
Ich habe die zip über Clone/ Download ZIP heruntergeladen, welche Datei muss ich nun genau anklicken, damit es in Safari auswählbar erscheint? Das Developer Menü in Safari habe ich erfolgreich aktiviert).
Vorab vielen Dank!

**Comment by derzoelli** [comment]
Hey. Kein Problem. Mittlerweile ist das Plugin als Beta über Testflight verfügbar. Sowohl für iOS als auch für MacOS. 
Du musst dir nur die App "Testflight" aus dem Store laden und über folgenden Link einmal beitreten: https://testflight.apple.com/join/CVIYsv2P

Anschließend kannst du Binnen-I über Testflight installieren. Ist deutlich einfacher als alles andere :) 
Solltest du dabei noch nen Problem haben, helfe ich dir gerne weiter.

**Comment by mansle** [comment]
Wow, super! Deutlich einfacher als ich mir das vorgestellt habe.
